# My prefix key
unbind-key C-b
set-option -g prefix C-j

# source tmux
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# get my vim colors up in here
set -g default-terminal "screen-256color"

# Saner splitting.
bind v split-window -h
bind s split-window -v

# Vim-style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Vim-style selection and copy
# Setup 'v' to begin selection as in Vim
# C-[ to start copy mode, C-] to paste after
bind -Tcopy-mode-vi v send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

set-window-option -g mode-keys vi

# Fix slow escaping to normal mode
set -sg escape-time 0

# start numbering windows @ 1
set -g base-index 1

# start numbering panes @ 1
set-window-option -g pane-base-index 1

# pane number display
set-option -g display-panes-active-colour blue #blue
set-option -g display-panes-colour brightred #orange

# clock
set-window-option -g clock-mode-colour green #green
